apiVersion: v2
name: oai-5g-basic
type: application
icon: http://www.openairinterface.org/wp-content/uploads/2015/06/cropped-oai_final_logo.png
version: v1.5.1
description: OAI 5G Release 16 Core Network

appVersion: develop-v1.5.1

keywords:
  - UPF
#  - Traffic_server

maintainers:
  - name:  OPENAIRINTERFACE
    email: contact@openairinterface.org

dependencies:
- condition: oai-spgwu-tiny.enabled
  name: oai-spgwu-tiny
  repository: "file://../oai-spgwu-tiny"
  version: v1.5.1
  #- condition: oai-traffic-server.enabled
  #name: oai-traffic-server
  #repository: "file://../oai-traffic-server"
  #version: v1

